image: Visual Studio 2017

branches:
  except:
    - gh-pages

skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - README.md
    - CHANGELOG.md
    - LICENSE

skip_tags: false

test: off

init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
    }

after_build:
- ps: >-
    $wc = New-Object System.Net.WebClient

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path "NetCoreClrTestResults.xml"))

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path "DesktopClrTestResults.xml"))

on_success:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        nuget push ".\build\Castle.Core.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.Services.Logging.log4netIntegration.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.Services.Logging.NLogIntegration.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.Services.Logging.SerilogIntegration.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
    }

build_script:
- cmd: build.cmd

artifacts:
- path: build\*.nupkg
  name: core
